// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package adapter

import (
	"golang-container-to-wire.com/pkg/adapter/logrus"
	"golang-container-to-wire.com/pkg/adapter/viper"
)

// Injectors from wire.go:

func CreateEnvironment() viper.Viper {
	viperViper := viper.CreateAdapter()
	return viperViper
}

func CreateLogger() logrus.Logrus {
	viperViper := viper.CreateAdapter()
	logrusLogrus := logrus.CreateAdapter(viperViper)
	return logrusLogrus
}
